import re

from app.rag.retriever import retrieve
from app.integrations.gemini import generate_answer


def answer_question(
    query: str,
    top_k: int = 5,
    source: str | None = None,
    project_id: str | None = None,
) -> dict:

    # ========================================================
    # 1. Retrieve relevant evidence
    # ========================================================

    results = retrieve(
        query=query,
        top_k=top_k,
        source=source,
        project_id=project_id,
    )

    if not results:
        return {
            "answer": (
                "I don't have enough relevant information "
                "in the provided research."
            ),
            "citations": [],
            "citation_validation": {
                "valid": True,
                "cited_evidence": [],
                "invalid_evidence": []
            }
        }

    # ========================================================
    # 2. Build numbered evidence context
    # ========================================================

    context_parts = []

    for i, result in enumerate(
        results,
        start=1
    ):

        context_parts.append(
            f"""
[Evidence {i}]
Source: {result["source"]}
Page: {result["page"]}

{result["text"]}
"""
        )

    context = "\n\n".join(
        context_parts
    )

    # ========================================================
    # 3. Ask Gemini for evidence-grounded answer
    # ========================================================

    prompt = f"""
You are a research assistant.

Answer the user's question using ONLY the research
evidence provided below.

IMPORTANT CITATION RULES:

1. Every factual claim must have a citation.
2. Use exactly this citation format:
   [Evidence N]
3. N must correspond to an evidence number provided below.
4. Never create an evidence number that does not exist.
5. Do not cite evidence that does not support the claim.
6. If the evidence is insufficient, explicitly say so.
7. Do not use outside knowledge.
8. Keep the answer concise and research-oriented.
9. Only cite evidence that you actually use to support
   a statement.

Research Evidence:
------------------
{context}
------------------

User Question:
{query}

Write the answer now.
"""

    answer = generate_answer(
        prompt
    )

    # ========================================================
    # 4. Validate citations generated by Gemini
    # ========================================================

    valid_evidence_ids = set(
        range(
            1,
            len(results) + 1
        )
    )

    cited_ids = set()

    matches = re.findall(
        r"\[Evidence\s+(\d+)\]",
        answer
    )

    for match in matches:

        evidence_id = int(match)

        if evidence_id in valid_evidence_ids:
            cited_ids.add(
                evidence_id
            )

    # ========================================================
    # 5. Build citations ONLY for evidence actually cited
    # ========================================================

    citations = []

    for evidence_id in sorted(
        cited_ids
    ):

        result = results[
            evidence_id - 1
        ]

        citations.append(
            {
                "id": evidence_id,
                "source": result["source"],
                "page": result["page"],
                "distance": result["distance"]
            }
        )

    # ========================================================
    # 6. Detect invalid citations
    # ========================================================

    invalid_citations = []

    for match in matches:

        evidence_id = int(match)

        if evidence_id not in valid_evidence_ids:
            invalid_citations.append(
                evidence_id
            )

    # ========================================================
    # 7. Return final result
    # ========================================================

    return {
        "answer": answer,
        "citations": citations,
        "citation_validation": {
            "valid": len(
                invalid_citations
            ) == 0,

            "cited_evidence": sorted(
                cited_ids
            ),

            "invalid_evidence": sorted(
                set(invalid_citations)
            )
        }
    }
